In [1]:
from imports import *

In [9]:
def spikes_count(base_folder, local_path, *args, **kwargs):
    bk.load.current_session_linux(base_folder, local_path)
    neurons, metadata = bk.load.spikes()
    states = bk.load.states(True)

    n_spikes = {'REM': [],
                'NREM': [],
                'WAKE': []}
    for n in neurons:
        n_spikes['REM'].append(len(n.restrict(states['REM'])))
        n_spikes['NREM'].append(len(n.restrict(states['NREM'])))
        n_spikes['WAKE'].append(len(n.restrict(states['WAKE_HOMECAGE'])))

    metadata['n_spikes_REM'] = n_spikes['REM']
    metadata['n_spikes_NREM'] = n_spikes['NREM']
    metadata['n_spikes_WAKE'] = n_spikes['WAKE']
    return metadata

In [10]:
def merge(batch):
    array = []
    meta = []
    for sess,b in batch.items():
        array.append(b[0])
        meta.append(b[1])
    return np.hstack(array),pd.concat(meta)

In [11]:
bk.load.current_session_linux()
spikes_count(bk.load.base,'Rat08/Rat08-20130713')

Rat : 8 on day : 6
Working with session Rat08-20130713 @ /mnt/electrophy/Gabrielle/GG-Dataset-Light/Rat08/Rat08-20130713
Rat : 8 on day : 6
Working with session Rat08-20130713 @ /mnt/electrophy/Gabrielle/GG-Dataset-Light/Rat08/Rat08-20130713
Data already saved in Numpy format, loading them from here:
Rat08-20130713-neurons.npy
Rat08-20130713-metadata.npy

    Rat Day Shank Id Region Type  n_spikes_REM  n_spikes_NREM  n_spikes_WAKE
0     8   6     1  2    Hpc  Pyr          1731           5923           3959
1     8   6     2  2    Hpc  Pyr          1895          10521           9117
2     8   6     2  3    Hpc  Pyr          1568           8593           3168
3     8   6     2  4    Hpc  Pyr          2899          13323           1890
4     8   6     2  5    Hpc  Pyr          6377          28772          11696
..   ..  ..   ... ..    ...  ...           ...            ...            ...
247   8   6    19  2    BLA  Pyr          1898           5522           1314
248   8   6    19  3    BLA  Pyr           149           1303            337
249   8   6    19  4    BLA  Pyr           219           1008            336
250   8   6    19  5    BLA  Pyr           251            787            439
251   8   6    19  6    BLA  Pyr          1134           2788           1517

[252 rows x 9 columns]

In [12]:
batch, meta = bk.load.batch(spikes_count)

100%|██████████| 61/61 [06:01<00:00,  5.93s/it]

Batch finished in 361.8249852657318
Some session were not processed correctly
['Rat08-20130720', 'Rat08-20130722', 'Rat09-20140407', 'Rat09-20140408', 'Rat09-20140409', 'Rat11-20150402', 'Rat11-20150403']
11.475409836065573 %

In [13]:
n_spikes = pd.concat(batch)
# n_spikes.to_csv('/mnt/electrophy/Gabrielle/GG-Dataset-Light/All-Rats/States/n_spikes.csv',index = False)

In [14]:
fr = pd.read_csv(bk.load.base+'/All-Rats/States/fr_states.csv')

In [18]:
pd.merge(fr,n_spikes)

,Rat,Day,Shank,Id,Region,Type,wake,drowsy,WAKE_HOMECAGE,NREM,REM,SLEEP,n_spikes_REM,n_spikes_NREM,n_spikes_WAKE
0,8,1,4,2,Hpc,Pyr,0.553571,0.371076,0.604555,0.873333,1.995636,1.038426,3201,8122,5245
1,8,1,4,3,Hpc,Pyr,0.689208,0.933857,0.749210,0.725484,0.658978,0.715701,1057,6747,6500
2,8,1,4,4,Hpc,Int,0.265140,0.178251,0.334955,0.398710,0.304863,0.384905,489,3708,2906
3,8,1,4,5,Hpc,Pyr,1.005745,1.386771,1.278268,1.118065,0.517456,1.029714,830,10398,11090
4,8,1,4,6,Hpc,Pyr,0.488509,0.815022,0.586920,0.384409,0.314214,0.374083,504,3575,5092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6700,11,20,18,14,Hpc,Pyr,2.695594,4.007692,2.887911,1.320266,0.655777,1.195107,823,7140,40762
6701,11,20,18,15,Hpc,Int,9.263293,8.361538,9.062679,8.589497,5.254980,7.961429,6595,46452,127917
6702,11,20,20,2,Hpc,Pyr,3.335514,1.761538,3.267870,2.153476,7.678884,3.194207,9637,11646,46125
6703,11,20,20,3,Hpc,Pyr,0.302867,0.269231,0.286652,2.248706,2.733865,2.340087,3431,12161,4046
6704,11,20,20,4,Hpc,Pyr,5.070297,3.061538,5.253247,2.112056,1.285259,1.956326,1613,11422,74148

In [5]:
def filter_neurons(neurons,metadata,region,type):
    return neurons[(metadata.Region == region) & (metadata.Type == type)]

In [7]:
n_spikes_rem, metadata = merge(batch)
meta

                Rat  Day
Rat08-20130708    8    1
Rat08-20130709    8    2
Rat08-20130710    8    3
Rat08-20130711    8    4
Rat08-20130712    8    5
Rat08-20130713    8    6
Rat08-20130715    8    7
Rat08-20130716    8    8
Rat08-20130717    8    9
Rat08-20130718    8   10
Rat08-20130719    8   11
Rat09-20140324    9    1
Rat09-20140325    9    2
Rat09-20140326    9    3
Rat09-20140327    9    4
Rat09-20140328    9    5
Rat09-20140329    9    6
Rat09-20140331    9    7
Rat09-20140401    9    8
Rat09-20140402    9    9
Rat09-20140403    9   10
Rat09-20140404    9   11
Rat09-20140405    9   12
Rat10-20140619   10    1
Rat10-20140620   10    2
Rat10-20140622   10    3
Rat10-20140624   10    4
Rat10-20140626   10    5
Rat10-20140627   10    6
Rat10-20140628   10    7
Rat10-20140629   10    8
Rat10-20140701   10    9
Rat10-20140702   10   10
Rat10-20140703   10   11
Rat10-20140704   10   12
Rat10-20140705   10   13
Rat10-20140707   10   14
Rat10-20140708   10   15
Rat11-20150310   11    2
Rat11-20150312   11    3
Rat11-20150313   11    4
Rat11-20150314   11    5
Rat11-20150315   11    6
Rat11-20150316   11    7
Rat11-20150317   11    8
Rat11-20150321   11   11
Rat11-20150323   11   12
Rat11-20150325   11   14
Rat11-20150326   11   15
Rat11-20150327   11   16
Rat11-20150328   11   17
Rat11-20150330   11   18
Rat11-20150331   11   19
Rat11-20150401   11   20

In [9]:
%matplotlib qt
bk.plot.cumsum_curves(filter_neurons(n_spikes_rem,metadata,'BLA','Pyr'),500)
plt.show()

In [35]:
bla = filter_neurons(n_spikes_rem,metadata,'BLA','Pyr')

In [37]:
len(bla[bla>500])

1110

In [1]:
%matplotlib qt
plt.hist(filter_neurons(n_spikes_rem,metadata,'BLA','Pyr'),500)
# plt.semilogx()

NameError: name 'plt' is not defined